Repository SimplifyERP/Amilma, pull requests merged in 2024-01, with the labels that each got.

#13 feature:list view changes for expense_claim and melting_claim
  amilma_custom/api/expense_claim.py
  amilma_custom/api/melting.py
Labels: bug

#14 api:outlet list against company
  amilma_custom/api/masters_data.py
Labels: good first issue

#15 Develop to Master Branch Merging
  amilma_custom/api/expense_claim.py
  amilma_custom/api/masters_data.py
  amilma_custom/api/melting.py
Labels: enhancement

#16 API:Masters API Outlet List Data Added Additionally Customer Name
  amilma_custom/api/masters_data.py
Labels: enhancement

#17 Develop
  amilma_custom/api/masters_data.py
Labels: enhancement

#18 masters api customer remove
  amilma_custom/api/masters_data.py
Labels: enhancement

#19 Develop
  amilma_custom/api/masters_data.py
Labels: enhancement

#20 Custom Field Added
  amilma_custom/amilma_custom/custom/company.json
  amilma_custom/api/sales_order.py
Labels: enhancement

#21 Custom Field Added
  amilma_custom/amilma_custom/custom/company.json
  amilma_custom/api/sales_order.py
Labels: enhancement

#22 discount and taxes
  amilma_custom/api/purchase_item_masters.py
  amilma_custom/api/sales_item_masters.py
Labels: enhancement

#23 Develop Branched to Master
  amilma_custom/api/purchase_item_masters.py
  amilma_custom/api/sales_item_masters.py
Labels: enhancement

#24 bug-fix-discount
  amilma_custom/api/dashboard.py
  amilma_custom/api/purchase_item_masters.py
  amilma_custom/api/sales_item_masters.py
Labels: bug

#25 Develop to Master Branch
  amilma_custom/api/dashboard.py
  amilma_custom/api/purchase_item_masters.py
  amilma_custom/api/sales_item_masters.py
Labels: bug

#26 Purchase Order
  amilma_custom/api/purchase_item_masters.py
  amilma_custom/api/sales_item_masters.py
Labels: bug

#27 Purchase Order
  amilma_custom/api/purchase_item_masters.py
  amilma_custom/api/sales_item_masters.py
Labels: enhancement

#28 purchase order creation bug fix
  amilma_custom/api/melting.py
  amilma_custom/api/purchase_order.py
Labels: bug

#29 Develop
  amilma_custom/api/melting.py
  amilma_custom/api/purchase_order.py
Labels: bug

#30 bug-fix:melting cliam validation
  amilma_custom/amilma_custom/doctype/melting_claim/melting_claim.py
Labels: bug

#31 Develop
  amilma_custom/amilma_custom/doctype/melting_claim/melting_claim.py
Labels: bug

#32 list_view:bug changes for melting claim
  amilma_custom/api/melting.py
Labels: enhancement

#33 api:changes in profile dashboard
  amilma_custom/api/profile_dashboard.py
Labels: documentation

#34 New Updates and Changes fix
  amilma_custom/api/melting.py
  amilma_custom/api/profile_dashboard.py
Labels: bug

#35 bug-fix:date format changes
  amilma_custom/api/expense_claim.py
  amilma_custom/api/payment_entry.py
  amilma_custom/api/purchase_order.py
  amilma_custom/api/sales_order.py
Labels: bug

#36 Develop
  amilma_custom/api/expense_claim.py
  amilma_custom/api/payment_entry.py
  amilma_custom/api/purchase_order.py
  amilma_custom/api/sales_order.py
Labels: bug

#37 api-activites-dashboard
  amilma_custom/amilma_custom/custom/employee_checkin.json
  amilma_custom/amilma_custom/doctype/melting_claim/melting_claim.json
  amilma_custom/api/activites_page.py
  amilma_custom/hooks.py
Labels: enhancement

#38 Develop
  amilma_custom/amilma_custom/custom/employee_checkin.json
  amilma_custom/amilma_custom/doctype/melting_claim/melting_claim.json
  amilma_custom/api/activites_page.py
  amilma_custom/hooks.py
Labels: enhancement

#39 activities page empty string change to empty array
  amilma_custom/amilma_custom/doctype/melting_claim/melting_claim.py
  amilma_custom/api/activites_page.py
Labels: bug, documentation

#40 Changes in Meting Claim and Activites file
  amilma_custom/amilma_custom/doctype/melting_claim/melting_claim.py
  amilma_custom/api/activites_page.py
Labels: documentation

#41 feature:api for melting item masters
  amilma_custom/api/activites_page.py
  amilma_custom/api/melting.py
Labels: bug

#42 Develop
  amilma_custom/api/activites_page.py
  amilma_custom/api/melting.py
Labels: bug

#43 lead:custom field added
  amilma_custom/amilma_custom/custom/lead.json
  amilma_custom/hooks.py
Labels: enhancement

#44 Develop
  amilma_custom/amilma_custom/custom/lead.json
  amilma_custom/hooks.py
Labels: enhancement

#46 Develop
  amilma_custom/amilma_custom/custom/customer.json
Labels: enhancement

#47 corrected:changes in list view
  amilma_custom/api/dashboard.py
  amilma_custom/api/masters_data.py
  amilma_custom/api/outlet.py
  amilma_custom/hooks.py
Labels: documentation

#49 melting claims item masters
  amilma_custom/api/melting.py
Labels: enhancement

#50 Develop to Masters
  amilma_custom/api/melting.py
Labels: enhancement

#51 bug-fix:list view for customer doctype
  amilma_custom/amilma_custom/custom/customer.json
  amilma_custom/api/outlet.py
Labels: bug

#52 Develop
  amilma_custom/amilma_custom/custom/customer.json
  amilma_custom/api/outlet.py
Labels: bug

#53 feature:dashboard api with data
  amilma_custom/api/dashboard.py
  amilma_custom/api/payment_entry.py
Labels: enhancement

#54 Develop
  amilma_custom/api/dashboard.py
  amilma_custom/api/payment_entry.py
Labels: enhancement

#55 updates:payment entry and dashboard
  amilma_custom/amilma_custom/custom/sales_order.json
  amilma_custom/amilma_custom/custom/sales_order_item.json
  amilma_custom/amilma_custom/report/billed_and_non_billed_summary/billed_and_non_billed_summary.py
  amilma_custom/api/dashboard.py
  amilma_custom/api/outlet.py
  amilma_custom/api/payment_entry.py
  amilma_custom/hooks.py
Labels: enhancement

#56 New Updates in Development
  amilma_custom/amilma_custom/custom/sales_order.json
  amilma_custom/amilma_custom/custom/sales_order_item.json
  amilma_custom/amilma_custom/report/billed_and_non_billed_summary/billed_and_non_billed_summary.py
  amilma_custom/api/dashboard.py
  amilma_custom/api/outlet.py
  amilma_custom/api/payment_entry.py
  amilma_custom/hooks.py
Labels: enhancement

#58 Develop
  amilma_custom/api/dashboard.py
Labels: bug

#59 dashboard-api:added a log type of employee checkin
  amilma_custom/api/dashboard.py
Labels: enhancement

#60 Dashboard API New Added IN DICT
  amilma_custom/api/dashboard.py
Labels: enhancement

#61 feature:Dashboard API masters added sales invoice id
  amilma_custom/api/masters_data.py
Labels: enhancement

#62 Dashboard API added Sales Invoice ID
  amilma_custom/api/masters_data.py
Labels: enhancement

#63 developmemt:sales invoice id api
  amilma_custom/api/dashboard.py
  amilma_custom/api/masters_data.py
  amilma_custom/api/sales_invoice.py
Labels: enhancement

#64 Develop to Master
  amilma_custom/api/dashboard.py
  amilma_custom/api/masters_data.py
  amilma_custom/api/sales_invoice.py
Labels: enhancement

#65 feature:sales invoice gst filling script report
  amilma_custom/amilma_custom/custom/lead.json
  amilma_custom/amilma_custom/report/sales_gst_filling/__init__.py
  amilma_custom/amilma_custom/report/sales_gst_filling/sales_gst_filling.js
  amilma_custom/amilma_custom/report/sales_gst_filling/sales_gst_filling.json
  amilma_custom/amilma_custom/report/sales_gst_filling/sales_gst_filling.py
  amilma_custom/api/dashboard.py
Labels: enhancement

#66 Sales Invoice Report
  amilma_custom/amilma_custom/custom/lead.json
  amilma_custom/amilma_custom/report/sales_gst_filling/__init__.py
  amilma_custom/amilma_custom/report/sales_gst_filling/sales_gst_filling.js
  amilma_custom/amilma_custom/report/sales_gst_filling/sales_gst_filling.json
  amilma_custom/amilma_custom/report/sales_gst_filling/sales_gst_filling.py
  amilma_custom/api/dashboard.py
Labels: enhancement

#67 bug-fix:script report
  amilma_custom/amilma_custom/report/sales_gst_filling/sales_gst_filling.py
Labels: bug

#69 feature:dahsboard api changes
  amilma_custom/amilma_custom/report/sales_gst_filling/sales_gst_filling.py
  amilma_custom/api/dashboard.py
Labels: enhancement

#70 Report:Purchase Invoice GST Filing
  amilma_custom/amilma_custom/report/purchase_gst_filing/__init__.py
  amilma_custom/amilma_custom/report/purchase_gst_filing/purchase_gst_filing.js
  amilma_custom/amilma_custom/report/purchase_gst_filing/purchase_gst_filing.json
  amilma_custom/amilma_custom/report/purchase_gst_filing/purchase_gst_filing.py
Labels: enhancement

#71 Reports Created
  amilma_custom/amilma_custom/report/purchase_gst_filing/__init__.py
  amilma_custom/amilma_custom/report/purchase_gst_filing/purchase_gst_filing.js
  amilma_custom/amilma_custom/report/purchase_gst_filing/purchase_gst_filing.json
  amilma_custom/amilma_custom/report/purchase_gst_filing/purchase_gst_filing.py
  amilma_custom/amilma_custom/report/sales_gst_filling/sales_gst_filling.py
  amilma_custom/api/dashboard.py
Labels: enhancement

#72 bug-fix:sales invoice id
  amilma_custom/api/sales_invoice.py
Labels: bug

#73 Develop
  amilma_custom/api/sales_invoice.py
Labels: bug

#74 bug:Dashboard API Changes
  amilma_custom/api/dashboard.py
Labels: bug

#75 Develop to Master
  amilma_custom/api/dashboard.py
Labels: bug

#76 bug-fix:dashboard and script report
  amilma_custom/amilma_custom/report/purchase_gst_filing/purchase_gst_filing.py
  amilma_custom/amilma_custom/report/sales_gst_filling/sales_gst_filling.py
  amilma_custom/api/dashboard.py
Labels: bug

#77 Develop to Master
  amilma_custom/amilma_custom/report/purchase_gst_filing/purchase_gst_filing.py
  amilma_custom/amilma_custom/report/sales_gst_filling/sales_gst_filling.py
  amilma_custom/api/dashboard.py
Labels: bug

#78 report:purchase and sales invoice
  amilma_custom/amilma_custom/report/purchase_gst_filing/purchase_gst_filing.py
  amilma_custom/amilma_custom/report/sales_gst_filling/sales_gst_filling.py
Labels: bug

#79 Develop to Master
  amilma_custom/amilma_custom/report/purchase_gst_filing/purchase_gst_filing.py
  amilma_custom/amilma_custom/report/sales_gst_filling/sales_gst_filling.py
Labels: bug

#80 bug-fix:dashboard activites api
  amilma_custom/api/dashboard.py
Labels: bug

#81 Develop to Master Branch
  amilma_custom/api/dashboard.py
Labels: bug

#82 api:acitvites page api bug fix
  amilma_custom/api/activites_page.py
Labels: bug

#83 Develop to master
  amilma_custom/api/activites_page.py
Labels: bug

#84 API:Dashboard API Bug Fixed
  amilma_custom/api/dashboard.py
Labels: bug
