Repository SimplifyERP/Amilma, pull requests merged in 2024-03, with the labels that each got.

#21 feature:webform created in opportunity
  amilma_custom/amilma_custom/custom/opportunity.json
  amilma_custom/amilma_custom/doctype/district/__init__.py
  amilma_custom/amilma_custom/doctype/district/district.js
  amilma_custom/amilma_custom/doctype/district/district.json
  amilma_custom/amilma_custom/doctype/district/district.py
  amilma_custom/amilma_custom/doctype/district/test_district.py
  amilma_custom/amilma_custom/doctype/pincode/__init__.py
  amilma_custom/amilma_custom/doctype/pincode/pincode.js
  amilma_custom/amilma_custom/doctype/pincode/pincode.json
  amilma_custom/amilma_custom/doctype/pincode/pincode.py
  amilma_custom/amilma_custom/doctype/pincode/test_pincode.py
  amilma_custom/amilma_custom/web_form/__init__.py
  amilma_custom/amilma_custom/web_form/opportunity/__init__.py
  amilma_custom/amilma_custom/web_form/opportunity/opportunity.js
  amilma_custom/amilma_custom/web_form/opportunity/opportunity.json
  amilma_custom/amilma_custom/web_form/opportunity/opportunity.py
Labels: enhancement

#25 Feature fields changes
  amilma_custom/amilma_custom/web_form/opportunity/opportunity.json
  amilma_custom/fixtures/property_setter.json
  amilma_custom/hooks.py
Labels: enhancement

#27 feature:hidden distributor field
  amilma_custom/amilma_custom/custom/opportunity.json
  amilma_custom/fixtures/property_setter.json
  amilma_custom/hooks.py
Labels: enhancement

#28 Develop
  amilma_custom/amilma_custom/custom/opportunity.json
  amilma_custom/fixtures/property_setter.json
  amilma_custom/hooks.py
Labels: duplicate

#29 Feature sales purchase daily count report
  amilma_custom/amilma_custom/report/sku_wise__daily_purchase_in_box/__init__.py
  amilma_custom/amilma_custom/report/sku_wise__daily_purchase_in_box/sku_wise__daily_purchase_in_box.js
  amilma_custom/amilma_custom/report/sku_wise__daily_purchase_in_box/sku_wise__daily_purchase_in_box.json
  amilma_custom/amilma_custom/report/sku_wise__daily_purchase_in_box/sku_wise__daily_purchase_in_box.py
  amilma_custom/amilma_custom/report/sku_wise__daily_sales_in_box/sku_wise__daily_sales_in_box.py
  amilma_custom/amilma_custom/web_form/opportunity/opportunity.json
  amilma_custom/fixtures/property_setter.json
Labels: enhancement

#30 Develop
  amilma_custom/amilma_custom/report/sku_wise__daily_purchase_in_box/__init__.py
  amilma_custom/amilma_custom/report/sku_wise__daily_purchase_in_box/sku_wise__daily_purchase_in_box.js
  amilma_custom/amilma_custom/report/sku_wise__daily_purchase_in_box/sku_wise__daily_purchase_in_box.json
  amilma_custom/amilma_custom/report/sku_wise__daily_purchase_in_box/sku_wise__daily_purchase_in_box.py
  amilma_custom/amilma_custom/report/sku_wise__daily_sales_in_box/sku_wise__daily_sales_in_box.py
  amilma_custom/amilma_custom/web_form/opportunity/opportunity.json
  amilma_custom/fixtures/property_setter.json
Labels: enhancement

#31 feature:remove mandadory fields
  amilma_custom/amilma_custom/web_form/opportunity/opportunity.js
  amilma_custom/hooks.py
Labels: enhancement

#32 Develop
  amilma_custom/amilma_custom/web_form/opportunity/opportunity.js
  amilma_custom/hooks.py
Labels: enhancement

#33 feature:report correction for sales and purchase invoice against dail…
  amilma_custom/amilma_custom/report/sku_wise__daily_purchase_in_box/sku_wise__daily_purchase_in_box.py
  amilma_custom/amilma_custom/report/sku_wise__daily_sales_in_box/sku_wise__daily_sales_in_box.py
Labels: enhancement

#34 Develop
  amilma_custom/amilma_custom/report/sku_wise__daily_purchase_in_box/sku_wise__daily_purchase_in_box.py
  amilma_custom/amilma_custom/report/sku_wise__daily_sales_in_box/sku_wise__daily_sales_in_box.py
Labels: bug

#35 feature:bill number change to purchase gst filing report
  amilma_custom/amilma_custom/report/purchase_gst_filing/purchase_gst_filing.py
Labels: enhancement

#36 Develop
  amilma_custom/amilma_custom/report/purchase_gst_filing/purchase_gst_filing.py
Labels: bug

#37 feature:bill number changed
  amilma_custom/amilma_custom/report/purchase_gst_filing/purchase_gst_filing.py
Labels: enhancement

#38 Develop
  amilma_custom/amilma_custom/report/purchase_gst_filing/purchase_gst_filing.py
Labels: bug
